docs/create/getting-started/install.md
I missed this alias suggestion in the documentation and with this commit want to bring It back as It very useful I suppose
=> return of the lost alias suggestion

docs/validator/requirements.md
Hi Phi Labs team,
I was reviewing your validator docs for inspiration and spied an instance of "Tendermint" 
I applied other edits and spread a little grammar love around while I was in your doc
=> docs: replace Tendermint with Phi Labs and other edits

docs/create/advanced/daemon.md.disabled, docs/create/cli/_category_.json, docs/create/cli/cli.md, docs/create/cli/daemon.md, docs/create/getting-started/basics.md, docusaurus.config.js
This PR cleans up the 2 lingering items from Issue #71 (Page 1: What is archway cli really?, Page 2: What is archwayd really?)
- /docs/create/cli/daemon
- /docs/create/cli/cli
***
I think it's okay to merge, but might still need some love
=> Adds 2 new pages

docs/create/getting-started/basics.md, docusaurus.config.js
Updates CLI API docs/usage with new commands, and links to this doc from the homepage
=> Update CLI API docs

docs/create/getting-started/basics.md
Missed updating this flag in the last deployment
=> Adds update to CLI basics for 'archway build --optimize' flag

docs/overview/network.md
Partial delivery of Issue #98 
Updates public networks page with grpc urls
=> Adds grpc endpoints to public networks doc

docs/node/running-a-local-testnet.md, docs/validator/requirements.md, docs/validator/running-a-validator-node.mdx
Made edits to validator docs, remove reference to make on docker commands
=> edits to validator docs

plugins/docusaurus-google-tag-manager-plugin.js
[WEB-1]
[WEB-1]: https://phi-labs.atlassian.net/browse/WEB-1?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: use innerHTML to put script in correct place

docs/create/guides/my-first-dapp/interact.md
In this PR: 
- adds information to the [My First Dapp](https://docs.archway.io/docs/create/guides/my-first-dapp/interact) guide explaining that dapps collecting payments need to use the coin minimal denom for processing tx
- adds @macku99 as a CODEOWNER
=> Guides -> My First dapp (payment info)

content/2.developers/1.getting-started/1.install.md, content/2.developers/1.getting-started/2.setup.md, content/2.developers/1.getting-started/3.cosmwasm.md, content/2.developers/2.managing-dependencies.md, content/2.developers/3.debug.md, content/2.developers/4.troubleshoot.md, content/2.developers/5.archway-cli/1.introduction.md, content/2.developers/5.archway-cli/2.developer-cli.md, content/2.developers/5.archway-cli/3.daemon.md, content/2.developers/6.guides/1.my-first-dapp/1.start.md, content/2.developers/6.guides/1.my-first-dapp/2.faucet.md, content/2.developers/6.guides/1.my-first-dapp/3.wasm.md, content/2.developers/6.guides/1.my-first-dapp/4.deploy.md, content/2.developers/6.guides/1.my-first-dapp/5.interact.md, content/2.developers/6.guides/1.my-first-dapp/6.dapp.md, content/2.developers/6.guides/2.nft-project/1.start.md, content/2.developers/6.guides/2.nft-project/2.deploy.md, content/2.developers/6.guides/2.nft-project/3.interact.md, content/2.developers/6.guides/2.nft-project/4.dapp.md, content/3.validators/1.overview.md, content/3.validators/2.requirements.md, content/3.validators/3.running-a-validator-node.md, content/3.validators/4.monitoring-validators.md, content/3.validators/5.troubleshooting.md
move all content as per nuxt content.
=> all content from old docs

content/1.overview/2.rewards/4.consensus-fee.md
Changes to the Consensus Fee page
=> Consensus fee

data/useSectionCategories.ts
Update developers overview section categories
=> fix: update overview card and link

layouts/default.vue
=> fix: padding on content container

data/useHighlightedArticles.ts, domain/AlgoliaSearch.ts
Popular and recent were not showing up and should be fixed now.
=> fixed missing popular and recent

content/5.resources/1.networks.md
=> Added a warning that the Developer CLI no longer supports the Torii network

content/1.overview/3.join-the-community.md, content/1.overview/4.glossary.md
Set external links to open new window/tab and fix a broken link
=> Updates to the Overview section

content/2.developers/2.developer-tools/2.developer-cli.md
adjusted the overflows of content in the table
=> fixed table

content/2.developers/4.cosmwasm-documentation/3.architecture/7.comparison-with-ethereum.md
**Comparison to Ethereum:**
“This CosmWasm design decision helps reduce possible attack vectors.” → maybe a little elaboration here as we can reasonably expect users interested in this section to have some Solidity experience; Maybe mention at least one common attack vector;
**Smart Contact Instantiation:**
Maybe add an example here as this feature of separate instantiation is of particular interest when compared to Solidity contracts; Maybe use something similar to a vesting contract with different instantiations / parameters as an example;
**Lessons learned from Ethereum**
I would consider using a ordinal list here so that individual lessons can be easily referenced (with doc version); it may also be relevant to the first comment above;
=> Suggested changes

content/2.developers/2.developer-tools/4.arch3js/2.transaction-query-execution.md, content/2.developers/2.developer-tools/4.arch3js/3.tutorials/1.ibc-transaction.md, content/2.developers/2.developer-tools/4.arch3js/3.tutorials/2.store-instantiate-contract.md, content/2.developers/4.cosmwasm-documentation/2.getting-started/5.interact-with-contract.md, content/2.developers/4.cosmwasm-documentation/4.smart-contracts/9.verify.md, content/3.community/5.vote.md, content/4.validators/1.running-a-node/4.join-a-network.md, content/4.validators/1.running-a-node/5.configure.md, content/5.resources/2.ibc-channels.md
- Configure.md considered optional (restructured and added a note)
- changed constantine-1 to constantine-2
=> Revisit content

content/3.community/4.governance.md, content/5.resources/1.networks.md
=> Fix: typos

content/5.resources/1.networks.md
- updated blockexplorer link on "networks page"
=> updated blockexplorer link

content/4.validators/1.running-a-node/6.sync-with-state-sync.md, content/4.validators/1.running-a-node/7.sync-from-snapshot.md
- updated 6.sync-with-state-sync.md
- updated 7.sync-from-snapshot.md
to reflect the snapshot and state-sync provided by Autostake
=> added autostake state-sync and snapshot

content/2.developers/2.developer-tools/4.arch3js/2.transaction-query-execution.md
Give examples of how to query a contract, a core protocol endpoint using arch3.js archway client, and an API endpoint with an HTTP client.
=> Updates to the arch3.js query examples

content/4.validators/1.running-a-node/3.keys.md
=> updated keys.md

content/2.developers/1.getting-started/2.ide-setup.md, content/2.developers/2.developer-tools/3.daemon.md, content/2.developers/2.rewards/3.rewards-reference.md, content/2.developers/2.rewards/4.consensus-fee.md, content/2.developers/3.guides/1.guides-overview.md, content/2.developers/3.guides/3.my-first-dapp/1.start.md, content/2.developers/4.cosmwasm-documentation/3.architecture/1.multi-chain-contracts.md, content/4.validators/1.running-a-node/2.install.md, content/4.validators/1.running-a-node/4.join-a-network.md, content/4.validators/1.running-a-node/8.configure.md, content/4.validators/2.becoming-a-validator/1.overview.md, content/4.validators/2.becoming-a-validator/2.requirements.md, content/4.validators/2.becoming-a-validator/3.running-a-validator-node.md, content/4.validators/2.becoming-a-validator/4.monitoring-validators.md, content/4.validators/2.becoming-a-validator/6.running-a-local-testnet.md, content/4.validators/2.becoming-a-validator/9.troubleshooting.md, content/4.validators/3.running-a-relayer/2.running-a-relayer.md
fixed pages' title capitalization
=> fixed titles capitalization

content/5.resources/3.blockexplorers.md
Add archgregator.online dashboard
=> Add Explorer

content/4.validators/1.running-a-node/3.keys.md
=> updated keys management docs

content/2.developers/2.rewards/2.managing-rewards.md, content/2.developers/2.rewards/3.rewards-reference.md
- added content to managing-rewards.md
- added conten to rewards-reference.md
=> Review rewards section

content/4.validators/1.running-a-node/5.sync-from-genesis.md, content/4.validators/1.running-a-node/6.sync-with-state-sync.md, content/4.validators/1.running-a-node/7.sync-from-snapshot.md
- added the **--unsafe-skip-upgrades 1492500** flag in relevant commands
=> added unsafe-skip-upgrade flag

content/2.developers/2.developer-tools/2.developer-cli.md, content/2.developers/3.guides/3.my-first-dapp/1.start.md, content/2.developers/3.guides/3.my-first-dapp/2.wasm.md, content/2.developers/3.guides/3.my-first-dapp/3.deploy.md, content/2.developers/3.guides/3.my-first-dapp/4.interact.md, content/2.developers/3.guides/4.nft-project/2.deploy.md, content/2.developers/3.guides/4.nft-project/3.interact.md
- added links and enhanced content in developer-cli.md
- added archwayd commands in interact.md, deploy.md, mint.md pages.
- minor improvements
=> enhance guides

content/2.developers/4.cosmwasm-documentation/6.tutorials/1.simple-option/1.testing.md, content/2.developers/4.debug.md, content/2.developers/5.managing-dependencies.md
- added introduction to testing.md
- added introduction to debugging.md
- added cargo commands and workspaces overview to dependencies.md
=> Review cosmwasm tutorials

content/5.resources/2.ibc-channels.md
- update ibc channel to reflect changes from osmo-4 to osmo-5
=> updated ibc channels to osmo-5

content/2.developers/3.guides/3.my-first-dapp/3.deploy.md, content/3.community/1.wallet-setup/2.keplr-setup.md, content/3.community/1.wallet-setup/3.cosmostation-setup.md, content/4.validators/1.running-a-node/3.keys.md, content/4.validators/2.becoming-a-validator/10.troubleshooting.md, content/4.validators/2.becoming-a-validator/2.requirements.md, content/4.validators/2.becoming-a-validator/3.running-a-validator-node.md, content/4.validators/2.becoming-a-validator/6.running-a-local-testnet.md
correcting typos
adding punctuation
adding external guides
=> add external guides, correect typos and add punctuation

content/2.developers/2.developer-tools/4.arch3js/1.introduction.md
- Corrected missed spellings
- Fixed grammatical errors
- External links open in new tab or window
=> Corrected missed spellings and fixed grammatical errors

content/4.validators/2.becoming-a-validator/3.running-a-validator-node.md
- updated docs to reflect archway's specific requirement for gentx
=> added gentx fees flag

content/2.developers/2.developer-tools/4.arch3js/3.tutorials/2.store-instantiate-contract.md
Updates to the store and instantiate example where the upload and instantiate functions are now being used
=> Updates to the store and instantiate example

content/4.validators/1.running-a-node/2.install.md, content/4.validators/1.running-a-node/5.join-a-network/2.sync-from-genesis.md, content/4.validators/1.running-a-node/5.join-a-network/3.sync-with-state-sync.md, content/4.validators/1.running-a-node/5.join-a-network/4.sync-from-snapshot.md, content/4.validators/2.becoming-a-validator/3.running-a-validator-node.md, content/4.validators/2.becoming-a-validator/5.cosmovisor.md
- updated decimal precision and added mainnet example
- redirect to pre-built binary
- updated chain id in examples
- removed unnecessary flags
=> Update validator docs

content/4.validators/2.becoming-a-validator/9.upgrades-history.md
=> updated upgrades history

content/1.overview/8.security.md
=> added security policy link

content/2.developers/2.developer-tools/3.daemon.md, content/3.community/1.wallet-setup/4.leap-setup.md, content/3.community/4.governance/4.governance.md, content/3.community/4.governance/5.vote.md
=> added youtube embeds

content/2.developers/2.developer-tools/2.developer-cli.md, content/2.developers/3.guides/3.my-first-dapp/3.deploy.md, content/2.developers/3.guides/4.nft-project/2.deploy.md
- updated developer-cli.md , deploy.md files with premium info
=> Update cli docs

components/content/IBC/RelayersTable.vue, content/5.resources/2.ibc-channels.md
- updated ibc channels component for mainnet
=> add ibc channel component for mainnet

content/4.validators/1.running-a-node/5.join-a-network/2.sync-from-genesis.md, content/4.validators/1.running-a-node/5.join-a-network/3.sync-with-state-sync.md, content/4.validators/1.running-a-node/5.join-a-network/4.sync-from-snapshot.md, content/5.resources/1.networks.md
- fixed links
- added clarifications
=> Docs review

content/2.developers/4.cosmwasm-documentation/4.smart-contracts/10.migration.md
Shows how to execute migrations from archwayd, arch3.js and archway cli and also how to make contract mutable and immutable.
=> Make contracts mutable and immutable using archwayd, arch3.js and archway cli

content/3.community/2.staking/5.archway-connect-staking.md, content/3.community/3.managing-tokens/3.bridge-tokens.md, content/3.community/7.archway-connect.md
=> Docs review 1

content/2.developers/2.developer-tools/4.arch3js/3.tutorials/4.websockets.md
- updated websockets page to reflect latest implementation
=> updated websockets page

content/2.developers/1.getting-started/1.install.md, content/2.developers/2.developer-tools/3.daemon.md, content/2.developers/7.troubleshoot.md, content/4.validators/1.running-a-node/1.prerequisites.md, content/4.validators/1.running-a-node/2.install.md, content/4.validators/1.running-a-node/3.initialization.md, content/4.validators/1.running-a-node/4.keys.md, content/4.validators/1.running-a-node/5.join-a-network/2.sync-from-genesis.md, content/4.validators/1.running-a-node/5.join-a-network/3.sync-with-state-sync.md, content/4.validators/1.running-a-node/5.join-a-network/4.sync-from-snapshot.md, content/4.validators/2.becoming-a-validator/3.running-a-validator-node.md, content/4.validators/2.becoming-a-validator/7.chain-upgrade.md, content/4.validators/2.becoming-a-validator/8.upgrades-history.md
- update docs to reflect archwayd changes to v2.0.0
=> Update release info

content/2.developers/2.developer-tools/5.swagger.md
=> updated swagger page

content/2.developers/2.rewards/2.managing-rewards.md
- fixed broken links in rewards page
=> fixed broken links

content/2.developers/2.rewards/3.rewards-reference.md, content/2.developers/3.guides/3.my-first-dapp/3.deploy.md, content/2.developers/3.guides/3.my-first-dapp/4.interact.md, content/2.developers/3.guides/4.nft-project/2.deploy.md, content/2.developers/3.guides/5.fee-grant/2.grant-allowance.md, content/2.developers/4.cosmwasm-documentation/2.getting-started/5.interact-with-contract.md, content/2.developers/6.managing-dependencies.md, content/2.developers/7.troubleshoot.md, content/3.community/4.governance/1.governance.md, content/4.validators/2.becoming-a-validator/3.running-a-validator-node.md
There are multiple commands which have the fees or gas prices manually set. These have now been revised to values generated dynamically.
=> Update arbitrary gas and fee values to be dynamic throughout the documentation

content/5.resources/4.ibc-denoms.md
Resource that list all native and IBC denoms within the Archway network.
=> Ibc denoms

content/2.developers/2.developer-tools/3.daemon.md, content/4.validators/1.running-a-node/2.install.md
=> updating sha256 checksum

content.config.ts, content/4.validators/2.becoming-a-validator/3.running-a-validator-node.md
- fixed commands
- updated archwayd version to v4.0.0
=> Update archway version

content/4.validators/2.becoming-a-validator/5.running-a-local-testnet.md
Add a note that the docker image should be changed to the debug version and the use of the new commands that should be executed to set up a new local docker testnet.
=> Add a note that the docker image should be changed to the debug version

content/3.community/10.community-calendar.md
- updated the Weekly Builders Call info
=> updated community_calls_page

content/2.developers/2.developer-tools/4.arch3js/1.introduction.md, content/2.developers/2.developer-tools/4.arch3js/3.tutorials/3.keplr-integration.md, content/2.developers/3.guides/3.my-first-dapp/5.dapp.md, content/2.developers/3.guides/5.fee-grant/3.utilize-grant.md
getOfflineSignerAuto… will detect which signer is needed and return either a DirectSigner or an AminoSigner.
=> Change getOfflineSigner to getOfflineSignerAuto

content/2.developers/2.developer-tools/4.arch3js/3.tutorials/4.websockets.md, content/3.community/10.community-calendar.md
- added wasm-CallMessage example
=> Update websocket docs

content/3.community/10.community-calendar.md
=> Update community calls page

content/4.validators/1.running-a-node/5.join-a-network/4.sync-from-snapshot.md
- updated sync-from-snapshot page
=> updated sync-from-snapshot page

content/3.community/10.community-calendar.md
=> updated link

content/2.developers/4.cosmwasm-documentation/6.tutorials/3.cosmwasm-by-example/1.math.md, content/2.developers/4.cosmwasm-documentation/6.tutorials/3.cosmwasm-by-example/2.instantiation.md, content/2.developers/4.cosmwasm-documentation/6.tutorials/3.cosmwasm-by-example/3.timelock.md, content/2.developers/4.cosmwasm-documentation/6.tutorials/3.cosmwasm-by-example/4.crowdfunding.md, content/2.developers/4.cosmwasm-documentation/6.tutorials/3.cosmwasm-by-example/5.responses-attributes.md, content/2.developers/4.cosmwasm-documentation/6.tutorials/3.cosmwasm-by-example/6.read-write-sate.md, content/2.developers/4.cosmwasm-documentation/6.tutorials/3.cosmwasm-by-example/7.sending-tokens.md, content/2.developers/4.cosmwasm-documentation/6.tutorials/3.cosmwasm-by-example/8.token-vault.md, content/2.developers/4.cosmwasm-documentation/6.tutorials/3.cosmwasm-by-example/9.amm-product.md
ADDED
- math.md
- instantiation.md
- timelock.md
- crowdfunding.md
- responses-attributes.md
- read-write-sate.md
- sending-tokens.md
- token-vault.md
- amm-product.md
=>  added cosmwasm by example docs

components/content/IBC/RelayersTable.vue, content/5.resources/2.ibc-channels.md, data/useRelayers.ts, domain/Relayers.ts
Match the changes on https://github.com/archway-network/networks/pull/212
=> fix: update relayers table to match networks repository changes

content/4.validators/1.running-a-node/5.join-a-network/3.sync-with-state-sync.md
Addition of links to the Kyve KSYNC documentation to the State Sync section of the docs.
=> Kyve state sync

content/4.validators/1.running-a-node/5.join-a-network/2.sync-from-genesis.md
This PR extends the sync from genesis section with the alternative of using validated and archived Archway data by KYVE through KSYNC.
=> Integrate KYVE into sync from genesis section

.github/workflows/deploy-uat-preview.yml, .github/workflows/deploy.yml, content/1.overview/4.cosmos-ibc-cosmwasm.md, content/2.developers/4.cosmwasm-documentation/6.tutorials/3.cosmwasm-by-example/1.math.md, content/2.developers/4.cosmwasm-documentation/6.tutorials/3.cosmwasm-by-example/2.instantiation.md, content/2.developers/4.cosmwasm-documentation/6.tutorials/3.cosmwasm-by-example/3.timelock.md, content/2.developers/4.cosmwasm-documentation/6.tutorials/3.cosmwasm-by-example/4.crowdfunding.md, content/2.developers/4.cosmwasm-documentation/6.tutorials/3.cosmwasm-by-example/5.responses-attributes.md, content/2.developers/4.cosmwasm-documentation/6.tutorials/3.cosmwasm-by-example/6.read-write-sate.md, content/2.developers/4.cosmwasm-documentation/6.tutorials/3.cosmwasm-by-example/7.sending-tokens.md, content/2.developers/4.cosmwasm-documentation/6.tutorials/3.cosmwasm-by-example/8.token-vault.md, content/2.developers/4.cosmwasm-documentation/6.tutorials/3.cosmwasm-by-example/9.amm-product.md, scripts/meilisearchIndexer.ts
Update script to validate objectID before trying to insert, also deleting obsolete indexes, and adding it to automation
=> fix: update meilisearch indexing

content/2.developers/6.resources/3.decentralized-storage.md
This change adds a detailed guide to interacting with the Jackal Outpost on archway.
=> Adding Jackal Storage to Docs
